---
- name: Playbook to add Linux clients to nagiosXI 
  remote_user: root
  hosts: nrpe_host
  vars: 
     - service:  
  tasks:
  - include_vars: ../vars/mysecrets.yml
  - name: Adding Host
    uri:
      url: 'http://192.168.0.30/nagiosxi/api/v1/config/service?apikey={{ apikey }}&pretty=1'
      method: POST
      body: 'host_name={{ ansible_hostname }}&service_description={{ item.service }}&check_command={{ item.command }}&check_interval=5&retry_interval=5&max_check_attempts=2&check_period=24x7&contacts=nagiosadmin&notification_interval=5&notification_period=24x7&applyconfig=1'
    register: result
    with_items:
      - { service: 'Ping', command: 'check_ping\!3000,80%\!5000,100%' }
      - { service: 'CPU Stats', command: "check_nrpe!check_cpu_stats!-a '-w 85 -c 95'" }
      - { service: 'Check uptime', command: "check_nrpe!check_uptime" }
      - { service: 'Cron Scheduling Daemon', command: "check_nrpe!check_init_service!-a 'cron'" }
      - { service: 'Nginx service', command: "check_nrpe!check_init_service!-a 'nginx'" }
      - { service: 'Postgresql Service', command: "check_nrpe!check_init_service!-a 'postgresql'" }
      - { service: 'Current Load', command: "check_nrpe!check_load!-a '-w 15,10,5 -c 30,20,10'" }
      - { service: 'Current Users', command: "check_nrpe!check_users!-a '-w 5 -c 10'" }
      - { service: 'Memory Usage', command: "check_nrpe!check_mem!-a '-w 20 -c 10'" }
      - { service: 'Swap Usage', command: "check_nrpe!check_swap!-a '-w 50% -c 20%'" }
      - { service: 'Root Partition', command: "check_nrpe!check_disk!-a '-w 20% -c 10% -p /'" }
      - { service: 'SSH', command: "check_nrpe!check_init_service!-a 'ssh'" }
      - { service: 'Open Files', command: "check_nrpe!check_open_files!-a '-w 30 -c 50'" }
      - { service: 'Total Processes', command: "check_nrpe!check_procs!-a '-w 150 -c 250'" }
      
    
...
